### ISSUE TITLE
Prometheus based metrics

### ISSUE THREAD

**Issue by arpitjindal97** [xgfone/go-apiserver#1]
Can we have an option to expose prometheus metrics ? Similar to what envoy exposes

You can take a look at them by running envoy server locally. Use below code and commands to have a working envoy routing to a microservice.

Run with:
```
docker run -it --rm -v ${PWD}/envoy.yaml:/etc/envoy/envoy.yaml -p 10000:10000 -p 8000:8000 envoyproxy/envoy-dev:latest
```
Visit: **localhost:8000/stats/prometheus**

**envoy.yaml**
```
node:
  cluster: front-envoy

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          tracing:
            provider:
              name: envoy.tracers.zipkin
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
                collector_cluster: jaeger
                collector_endpoint: "/api/v2/spans"
                shared_span_context: false
                collector_endpoint_version: HTTP_JSON
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_envoyproxy_io
  clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.1.19
                port_value: 8080
  - name: jaeger
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: jaeger
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.1.19
                port_value: 9411

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000
```

**main.go**
```
package main

import (
	"io"
	"log"
	"net/http"
)

func main() {
	// Set routing rules
	http.HandleFunc("/endpoint1", endpoint1)
	http.HandleFunc("/endpoint2", endpoint2)

	//Use the default DefaultServeMux.
	err := http.ListenAndServe(":8080", nil)
	if err != nil {
		log.Fatal(err)
	}
}

func endpoint1(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, "Endpoint 1")
}

func endpoint2(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, "Endpoint 2")
}
```
